server:
  port: 8080
  tomcat:
    uri-encoding: utf8
logging:
  level:
    support.yz.data: DEBUG
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/KVG?useSSL=false&useUnicode=true&characterEncoding=UTF-8
     username: root
     password: mary19931013
     driver-class-name: com.mysql.jdbc.Driver
  data:
     neo4j:
        uri: http://localhost:7474
        username: neo4j
        password: mary19931013
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.winter.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
