server:
  port: 8080
  tomcat:
    uri-encoding: utf8
logging:
  level:
    support.yz.data: DEBUG
spring:
  datasource:
     url: jdbc:mysql://dohko.mysql.001.master.hualala.com:3306/test2
     username: root
     password: hualaladev
     driver-class-name: com.mysql.jdbc.Driver
  data:
     neo4j:
        uri: http://localhost:7474
        username: neo4j
        password: 1234
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.winter.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
